### ISSUE TITLE
Good replacement for faust for non ML project?

### ISSUE THREAD

**Issue by ericsouza** [maki-nage/makinage#8]
Hi, I'm looking for a python framework to deal with kafka events with async consumers. My needs is not for Machine Learning, but just receive kafka messages, call external APIs and save some data in redis/postgres. Do you think this project is a good choice for that? Faust-streaming have a lot of cool stuff (windowed, tasks, timers, monitoring) but the project seems kind dead

**Comment by MainRo** [comment]
The focus of maki-nage is a little bit different than Faust (BTW building maki-nage on top of Faust was one of my early options). As you said, maki-nage is more focused on data-science use-cases. This means that we try to provide higher-level APIs and less flexibility than Faust.
Typically you will not be able to call async IOs in a maki-nage application for now. This may be possible in the future because we already have some similar needs, but this is not a priority for now.

However, if you need things like windowing operations, you can also go with your own AsyncIO application, and use [rxsci](https://github.com/maki-nage/rxsci/) for the data transforms. Bridging AsyncIO and rxsci is relatively easy both on the source and sink sides.

**Comment by ericsouza** [comment]
@MainRo Oh, I see. Thanks for the answer!!
